### ISSUE TITLE
simulate_de errors in Julia 1.10.4

### ISSUE THREAD

**Issue by zmorrell** [lanl-ansi/QuantumAnnealing.jl#49]
It is unclear whether this is being caused by the recent update of Julia to 1.10.4 or if it was caused by an update from OrdinaryDiffEq.jl. This needs to be fixed ASAP

**Comment by ccoffrin** [comment]
I agree we should get this fixed right away.

One quick fix would be to change the version bound requirements to keep the deps on previous versions that were working.

The better long term fix is to make everything compatible with the latest versions of the deps.

**Comment by zmorrell** [comment]
Resolved by #50
