### ISSUE TITLE
Custom annealing schedules

### ISSUE THREAD

**Issue by bernalde** [lanl-ansi/QuantumAnnealing.jl#9]
Hi Carleton, fantastic package, I think it will be really useful for some smaller experiments we have!
I would suggest that one could load an annealing schedule for an specific machine as available here https://docs.dwavesys.com/docs/latest/doc_physical_properties.html#anneal-schedules
That would allow people to have a closer simulation of a given DWave annealer.
Again, great contribution.

**Comment by ccoffrin** [comment]
Thanks @bernalde! We have support for this through the function `parse_dwave_annealing_schedule`. You can have a look at the prerelease docs (here)[https://lanl-ansi.github.io/QuantumAnnealing.jl/dev/] for more details.

**Comment by ccoffrin** [comment]
If you have ideas for other tools to support interoperability please let us know!

**Comment by ccoffrin** [comment]
I am going to close this for now as the requested feature is already available, as far as I can tell.
